import 'dotenv/config';
import { db } from './index';
import { properties } from './schema';

const seedData = [
  // Gurugram
  {
    name: "DLF Camellias",
    location: "Golf Course Road",
    city: "Gurugram",
    state: "Haryana",
    type: "apartment",
    bhk: "4BHK",
    sqft: 7300,
    priceInr: 5000,
    amenities: JSON.stringify(["Clubhouse", "Golf Course", "Spa", "Pool"]),
    builder: "DLF",
    possessionStatus: "ready",
    description: "Ultra luxury apartments in Gurugram"
  },
  {
    name: "M3M Golfestate",
    location: "Golf Course Ext Road",
    city: "Gurugram",
    state: "Haryana",
    type: "apartment",
    bhk: "3BHK",
    sqft: 3000,
    priceInr: 450,
    amenities: JSON.stringify(["Pool", "Gym", "Tennis Court", "Mini Theatre"]),
    builder: "M3M",
    possessionStatus: "ready",
    description: "Golf themed luxury residences"
  },
  {
    name: "Godrej Nature Plus",
    location: "Sohna Road",
    city: "Gurugram",
    state: "Haryana",
    type: "apartment",
    bhk: "2BHK",
    sqft: 1400,
    priceInr: 120,
    amenities: JSON.stringify(["Park", "Pool", "Gym", "Kids Area"]),
    builder: "Godrej",
    possessionStatus: "under-construction",
    description: "Health and wellness focused homes"
  },
  {
    name: "Emaar Palm Heights",
    location: "Sector 77",
    city: "Gurugram",
    state: "Haryana",
    type: "apartment",
    bhk: "3BHK",
    sqft: 2000,
    priceInr: 160,
    amenities: JSON.stringify(["Clubhouse", "Pool", "Gym"]),
    builder: "Emaar",
    possessionStatus: "ready",
    description: "Modern apartments with stunning views"
  },
  {
    name: "Tata Primanti",
    location: "Sector 72",
    city: "Gurugram",
    state: "Haryana",
    type: "villa",
    bhk: "4BHK",
    sqft: 4500,
    priceInr: 600,
    amenities: JSON.stringify(["Private Pool", "Garden", "Clubhouse"]),
    builder: "Tata Housing",
    possessionStatus: "ready",
    description: "Premium villas in a gated community"
  },
  {
    name: "Sobha City",
    location: "Sector 108",
    city: "Gurugram",
    state: "Haryana",
    type: "apartment",
    bhk: "3BHK",
    sqft: 2300,
    priceInr: 250,
    amenities: JSON.stringify(["Cricket Ground", "Pool", "Gym", "Clubhouse"]),
    builder: "Sobha",
    possessionStatus: "under-construction",
    description: "Urban park residences"
  },
  {
    name: "AIPL Joy Street",
    location: "Sector 66",
    city: "Gurugram",
    state: "Haryana",
    type: "commercial",
    bhk: null,
    sqft: 500,
    priceInr: 80,
    amenities: JSON.stringify(["Food Court", "Parking", "Security"]),
    builder: "AIPL",
    possessionStatus: "ready",
    description: "Premium commercial space"
  },
  {
    name: "Central Park Flower Valley",
    location: "Sohna",
    city: "Gurugram",
    state: "Haryana",
    type: "plot",
    bhk: null,
    sqft: 1800,
    priceInr: 100,
    amenities: JSON.stringify(["Park", "Clubhouse", "Security"]),
    builder: "Central Park",
    possessionStatus: "ready",
    description: "Premium plots in a township"
  },
  // Noida
  {
    name: "ATS Pious Hideaways",
    location: "Sector 150",
    city: "Noida",
    state: "UP",
    type: "apartment",
    bhk: "3BHK",
    sqft: 1600,
    priceInr: 150,
    amenities: JSON.stringify(["Pool", "Gym", "Clubhouse", "Squash Court"]),
    builder: "ATS",
    possessionStatus: "under-construction",
    description: "Spanish themed architecture"
  },
  {
    name: "Tata Eureka Park",
    location: "Sector 150",
    city: "Noida",
    state: "UP",
    type: "apartment",
    bhk: "2BHK",
    sqft: 1100,
    priceInr: 85,
    amenities: JSON.stringify(["Smart Home", "Pool", "Gym"]),
    builder: "Tata Housing",
    possessionStatus: "ready",
    description: "Smart homes with modern automation"
  },
  {
    name: "Gaur City 2",
    location: "Greater Noida West",
    city: "Noida",
    state: "UP",
    type: "apartment",
    bhk: "2BHK",
    sqft: 1000,
    priceInr: 65,
    amenities: JSON.stringify(["Stadium", "Mall", "School"]),
    builder: "Gaursons",
    possessionStatus: "ready",
    description: "Integrated township living"
  },
  {
    name: "Mahagun Moderne",
    location: "Sector 78",
    city: "Noida",
    state: "UP",
    type: "apartment",
    bhk: "4BHK",
    sqft: 2400,
    priceInr: 200,
    amenities: JSON.stringify(["Pool", "Gym", "Clubhouse", "Park"]),
    builder: "Mahagun",
    possessionStatus: "ready",
    description: "Luxury apartments in central Noida"
  },
  {
    name: "Logix Blossom County",
    location: "Sector 137",
    city: "Noida",
    state: "UP",
    type: "apartment",
    bhk: "3BHK",
    sqft: 1600,
    priceInr: 110,
    amenities: JSON.stringify(["Pool", "Gym", "Clubhouse"]),
    builder: "Logix",
    possessionStatus: "ready",
    description: "Premium residential project"
  },
  {
    name: "Jaypee Greens",
    location: "Greater Noida",
    city: "Noida",
    state: "UP",
    type: "villa",
    bhk: "4BHK",
    sqft: 4000,
    priceInr: 450,
    amenities: JSON.stringify(["Golf Course", "Clubhouse", "Pool"]),
    builder: "Jaypee",
    possessionStatus: "ready",
    description: "Golf centric premium villas"
  },
  {
    name: "Godrej Woods",
    location: "Sector 43",
    city: "Noida",
    state: "UP",
    type: "apartment",
    bhk: "3BHK",
    sqft: 1800,
    priceInr: 250,
    amenities: JSON.stringify(["Forest Theme", "Pool", "Gym"]),
    builder: "Godrej",
    possessionStatus: "under-construction",
    description: "Urban forest living"
  },
  // Mumbai
  {
    name: "Lodha World One",
    location: "Lower Parel",
    city: "Mumbai",
    state: "Maharashtra",
    type: "apartment",
    bhk: "4BHK",
    sqft: 3500,
    priceInr: 1500,
    amenities: JSON.stringify(["Observatory", "Pool", "Gym", "Spa"]),
    builder: "Lodha",
    possessionStatus: "ready",
    description: "Iconic luxury tower"
  },
  {
    name: "Runwal Elegante",
    location: "Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    type: "apartment",
    bhk: "3BHK",
    sqft: 1800,
    priceInr: 600,
    amenities: JSON.stringify(["Rooftop Garden", "Pool", "Gym"]),
    builder: "Runwal",
    possessionStatus: "ready",
    description: "Premium residences in Andheri"
  },
  {
    name: "Hiranandani Estate",
    location: "Thane",
    city: "Mumbai",
    state: "Maharashtra",
    type: "apartment",
    bhk: "2BHK",
    sqft: 900,
    priceInr: 150,
    amenities: JSON.stringify(["Hospital", "School", "Mall", "Clubhouse"]),
    builder: "Hiranandani",
    possessionStatus: "ready",
    description: "Integrated township in Thane"
  },
  {
    name: "L&T Seawoods Residences",
    location: "Navi Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    type: "apartment",
    bhk: "3BHK",
    sqft: 1400,
    priceInr: 220,
    amenities: JSON.stringify(["Transit Oriented", "Mall", "Pool"]),
    builder: "L&T Realty",
    possessionStatus: "ready",
    description: "Modern living connected to transit"
  },
  {
    name: "Godrej Trees",
    location: "Vikhroli",
    city: "Mumbai",
    state: "Maharashtra",
    type: "apartment",
    bhk: "2BHK",
    sqft: 1000,
    priceInr: 250,
    amenities: JSON.stringify(["Art Gallery", "Cafes", "Pool", "Gym"]),
    builder: "Godrej",
    possessionStatus: "ready",
    description: "Mixed use premium development"
  },
  // Bangalore
  {
    name: "Prestige Shantiniketan",
    location: "Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    type: "apartment",
    bhk: "3BHK",
    sqft: 1900,
    priceInr: 200,
    amenities: JSON.stringify(["Tech Park", "Mall", "Clubhouse"]),
    builder: "Prestige",
    possessionStatus: "ready",
    description: "Iconic township in Whitefield"
  },
  {
    name: "Brigade Cornerstone Utopia",
    location: "Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    type: "apartment",
    bhk: "2BHK",
    sqft: 1200,
    priceInr: 95,
    amenities: JSON.stringify(["Cineplex", "Retail", "Pool", "Gym"]),
    builder: "Brigade",
    possessionStatus: "under-construction",
    description: "Smart township"
  },
  {
    name: "Sobha Dream Acres",
    location: "Panathur",
    city: "Bangalore",
    state: "Karnataka",
    type: "apartment",
    bhk: "2BHK",
    sqft: 1000,
    priceInr: 80,
    amenities: JSON.stringify(["Multiple Pools", "Sports Courts", "Gym"]),
    builder: "Sobha",
    possessionStatus: "ready",
    description: "Premium homes for IT professionals"
  },
  {
    name: "Salarpuria Sattva Park Cubix",
    location: "Devanahalli",
    city: "Bangalore",
    state: "Karnataka",
    type: "apartment",
    bhk: "1BHK",
    sqft: 650,
    priceInr: 45,
    amenities: JSON.stringify(["Clubhouse", "Park", "Gym"]),
    builder: "Salarpuria Sattva",
    possessionStatus: "ready",
    description: "Compact homes near airport"
  },
  {
    name: "Purva Palm Beach",
    location: "Hennur",
    city: "Bangalore",
    state: "Karnataka",
    type: "apartment",
    bhk: "3BHK",
    sqft: 1600,
    priceInr: 140,
    amenities: JSON.stringify(["Wave Pool", "Beach Theme", "Gym"]),
    builder: "Puravankara",
    possessionStatus: "ready",
    description: "Beach themed luxury apartments"
  },
  {
    name: "Godrej Gold County",
    location: "Tumkur Road",
    city: "Bangalore",
    state: "Karnataka",
    type: "villa",
    bhk: "4BHK",
    sqft: 3200,
    priceInr: 350,
    amenities: JSON.stringify(["Private Garden", "Clubhouse", "Pool"]),
    builder: "Godrej",
    possessionStatus: "ready",
    description: "Premium villas in West Bangalore"
  },
  // Hyderabad
  {
    name: "My Home Bhooja",
    location: "HITEC City",
    city: "Hyderabad",
    state: "Telangana",
    type: "apartment",
    bhk: "4BHK",
    sqft: 3400,
    priceInr: 450,
    amenities: JSON.stringify(["Clubhouse", "Pool", "Gym", "Supermarket"]),
    builder: "My Home",
    possessionStatus: "ready",
    description: "Iconic luxury towers in HITEC City"
  },
  {
    name: "Aparna Serene Park",
    location: "Kondapur",
    city: "Hyderabad",
    state: "Telangana",
    type: "apartment",
    bhk: "3BHK",
    sqft: 1800,
    priceInr: 160,
    amenities: JSON.stringify(["Pool", "Gym", "Spa", "Park"]),
    builder: "Aparna",
    possessionStatus: "ready",
    description: "Peaceful living in bustling Kondapur"
  },
  {
    name: "Prestige High Fields",
    location: "Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    type: "apartment",
    bhk: "2BHK",
    sqft: 1200,
    priceInr: 110,
    amenities: JSON.stringify(["Disney Theme", "Pool", "Gym", "Clubhouse"]),
    builder: "Prestige",
    possessionStatus: "ready",
    description: "Disney themed premium apartments"
  },
  {
    name: "Rajapushpa Provincia",
    location: "Narsingi",
    city: "Hyderabad",
    state: "Telangana",
    type: "apartment",
    bhk: "3BHK",
    sqft: 2000,
    priceInr: 180,
    amenities: JSON.stringify(["Infinity Pool", "Gym", "Lounge"]),
    builder: "Rajapushpa",
    possessionStatus: "under-construction",
    description: "Ultra premium apartments near ORR"
  },
  {
    name: "Ramky Discovery City",
    location: "Srisailam Highway",
    city: "Hyderabad",
    state: "Telangana",
    type: "villa",
    bhk: "4BHK",
    sqft: 3000,
    priceInr: 250,
    amenities: JSON.stringify(["Clubhouse", "Park", "Security"]),
    builder: "Ramky",
    possessionStatus: "ready",
    description: "Integrated township living"
  },
  // Pune
  {
    name: "Kolte Patil Life Republic",
    location: "Hinjewadi",
    city: "Pune",
    state: "Maharashtra",
    type: "apartment",
    bhk: "2BHK",
    sqft: 1000,
    priceInr: 75,
    amenities: JSON.stringify(["School", "Fire Station", "Clubhouse", "Pool"]),
    builder: "Kolte Patil",
    possessionStatus: "ready",
    description: "Mega township near IT park"
  },
  {
    name: "Panchshil Towers",
    location: "Kharadi",
    city: "Pune",
    state: "Maharashtra",
    type: "apartment",
    bhk: "4BHK",
    sqft: 3000,
    priceInr: 400,
    amenities: JSON.stringify(["Concierge", "Pool", "Gym", "Lounge"]),
    builder: "Panchshil",
    possessionStatus: "ready",
    description: "Ultra luxury residences"
  },
  {
    name: "Rohan Tarang",
    location: "Wakad",
    city: "Pune",
    state: "Maharashtra",
    type: "apartment",
    bhk: "3BHK",
    sqft: 1500,
    priceInr: 120,
    amenities: JSON.stringify(["Pool", "Gym", "Park"]),
    builder: "Rohan",
    possessionStatus: "ready",
    description: "Well ventilated modern homes"
  },
  {
    name: "Pride World City",
    location: "Charholi",
    city: "Pune",
    state: "Maharashtra",
    type: "apartment",
    bhk: "2BHK",
    sqft: 900,
    priceInr: 60,
    amenities: JSON.stringify(["Clubhouse", "Lake", "Park"]),
    builder: "Pride Group",
    possessionStatus: "under-construction",
    description: "Upcoming integrated township"
  }
];

async function main() {
  console.log("Seeding properties...");
  try {
    for (const property of seedData) {
      await db.insert(properties).values(property);
    }
    console.log("Seeding complete!");
  } catch (error) {
    console.error("Error seeding:", error);
  } finally {
    process.exit(0);
  }
}

main();
